export default {
    synthConfig: {
        partials: [0.165, 0, 0.03, 0, 0.025, 0, 0.025, 0, 0.025, 0, 0.03, 0, 0.035, 0, 0, 0.085, 0.07],
        envelope: {
            "attack": 3.8,
            "attackCurve": "linear",
            "decay": 0.1,
            "release": 3.75,
            "releaseCurve": "linear",
            "sustain": 0.2
        }
    },
    tremoloConfig: {
        "wet": 0.00
    },
    vibratoConfig: {
        "depth": 0.1,
        "frequency": 5,
        "maxDelay": 0.005,
        "type": "sine",
        "wet": 0.3
    },
    phaserConfig: {
        "Q": 10,
        "baseFrequency": 350,
        "frequency": 0.5,
        "octaves": 3,
        "stages": 10,
        "wet": 0.2
    },
    feedbackDelayConfig: {
        "delayTime": 0.25,
        "feedback": 0.5,
        "wet": 0.25
    },
    chorusConfig: {
        "delayTime": 2.1,
        "depth": 0.4,
        "feedback": 0.1,
        "frequency": 0.85,
        "spread": 67,
        "type": "sine",
        "wet": 0.05
    },
    EQ3Config: {
        "high": "-12",
        "low": "-11",
        "mid": "-8"
    },
    reverbConfig: {
        "roomSize": 0.7,
        "dampening": 3000
    },
    filterConfig: {
        "Q": 0,
        "active": true,
        "frequency": 413,
        "rolloff": -12,
        "type": "lowpass"
    },
    loop: {
        core: [{
            "note": "D5",
            "velocity": 0.8,
            "start": "0:0",
            "duration": "2n"
        }, {
            "note": "E3",
            "velocity": 0.8,
            "start": "0:0",
            "duration": "2n"
        }, {
            "note": "C3",
            "velocity": 0.8,
            "start": "0:0",
            "duration": "2n"
        }, {
            "note": "C5",
            "velocity": 0.8,
            "start": "0:2",
            "duration": "2n"
        }, {
            "note": "Bb2",
            "velocity": 0.8,
            "start": "0:2",
            "duration": "2n"
        }, {
            "note": "D3",
            "velocity": 0.8,
            "start": "0:2",
            "duration": "2n"
        }, {
            "note": "Bb4",
            "velocity": 0.8,
            "start": "1:0",
            "duration": "2n"
        }, {
            "note": "C3",
            "velocity": 0.8,
            "start": "1:0",
            "duration": "2n"
        }, {
            "note": "A2",
            "velocity": 0.8,
            "start": "1:0",
            "duration": "2n"
        }, {
            "note": "A4",
            "velocity": 0.8,
            "start": "1:2",
            "duration": "2n"
        }, {
            "note": "Bb2",
            "velocity": 0.8,
            "start": "1:2",
            "duration": "2n"
        }, {
            "note": "G2",
            "velocity": 0.8,
            "start": "1:2",
            "duration": "2n"
        }, {
            "note": "C5",
            "velocity": 0.8,
            "start": "2:0",
            "duration": "2n"
        }, {
            "note": "D3",
            "velocity": 0.8,
            "start": "2:0",
            "duration": "2n"
        }, {
            "note": "Bb2",
            "velocity": 0.8,
            "start": "2:0",
            "duration": "2n"
        }, {
            "note": "Bb4",
            "velocity": 0.8,
            "start": "2:2",
            "duration": "2n"
        }, {
            "note": "C3",
            "velocity": 0.8,
            "start": "2:2",
            "duration": "2n"
        }, {
            "note": "A2",
            "velocity": 0.8,
            "start": "2:2",
            "duration": "2n"
        }, {
            "note": "A4",
            "velocity": 0.8,
            "start": "3:0",
            "duration": "2n"
        }, {
            "note": "Bb2",
            "velocity": 0.8,
            "start": "3:0",
            "duration": "2n"
        }, {
            "note": "G2",
            "velocity": 0.8,
            "start": "3:0",
            "duration": "2n"
        }, {
            "note": "F2",
            "velocity": 0.8,
            "start": "3:2",
            "duration": "2n"
        }, {
            "note": "G4",
            "velocity": 0.8,
            "start": "3:2",
            "duration": "2n"
        }, {
            "note": "A2",
            "velocity": 0.8,
            "start": "3:2",
            "duration": "2n",
            colorChange: true
        }],
    }
}